#直接使用environment环境，不使用脚本
#- name: Source the admin credentials to gain access to admin-only CLI commands
#  shell: . admin-openrc
#  args: 
#    chdir: /root
#    become: yes

- name: Create the glance user
  os_user: name=glance  password={{ glance_user_pass }} domain=default
#  shell: openstack user create --domain default --password-prompt glance
  environment: "{{ admin_env }}" 
  
- name: Add the admin role to the glance user and service project
  os_user_role: user=glance role=admin project=service
  environment: "{{ admin_env }}"
  
- name: Create the glance service entity
  os_keystone_service:
     name: glance
     service_type: image
     description: OpenStack Image
  environment: "{{ admin_env }}"
  
- name: Create the Image service API endpoints
  shell: openstack endpoint create --region RegionOne image {{ item }} http://controller:9292
  with_items:
      - public
      - internal
      - admin
  environment: "{{ admin_env }}"
  
- name: Install the packages
  apt: name=glance state=present
  
- name: Edit the /etc/glance/glance-api.conf file and complete the following actions
  template: src=glance-api.j2  dest=/etc/glance/glance-api.conf
  
- name: Edit the /etc/glance/glance-registry.conf file and complete the following actions
  template: src=glance-registry.j2 dest=/etc/glance/glance-registry.conf
  
- name: Sync glance database
  shell: sudo -s /bin/sh -c "glance-manage db_sync" glance
  become: yes
  
- name: Restart the Image services
  service: name={{ item }} state=restarted
  with_items:
    - glance-registry
    - glance-api
    
#验证glance
- name: Update cirros image to Controller Node
  copy: src=cirros-0.3.4-x86_64-disk.img dest=/root/cirros-0.3.4-x86_64-disk.img
  become: yes

#这里更新，成功解决了下面上传镜像的error
- name: Update system
  apt: update_cache=yes upgrade=dist

- name: Upload the image to the Image service using the QCOW2 disk format, bare container format, and public visibility so all projects can access it
  # shell: |
  #    export OS_USERNAME=admin
  #    export OS_PASSWORD={{ admin_pass }}
  #    export OS_PROJECT_NAME=admin
  #    export OS_USER_DOMAIN_NAME=Default
  #    export OS_PROJECT_DOMAIN_NAME=Default
  #    export OS_AUTH_URL=http://controller:35357/v3
  #    export OS_IDENTITY_API_VERSION=3
  #    openstack image create "cirros123"  --file /home/cirros-0.3.4-x86_64-disk.img --disk-format qcow2 --container-format bare --public
  os_image:   
    name: cirros_liutao
    container_format: bare 
    state: present
    filename: /root/cirros-0.3.4-x86_64-disk.img
    disk_format: qcow2
    is_public: yes
    kernel: cirros-vmlinuz
    ramdisk: cirros-initrd
    properties:
      cpu_arch: x86_64
      distro: ubuntu
  environment: "{{ admin_env }}"
  become: yes
  

