---

- hosts: controller-nodes
  roles:
  #  - ntp-controller
  #  - infracommon
  #  - dbserver-maria
  #  - rabbitserver
  #  - memcached
  #  - dbserver_population
  #  - keystone-n
   - glance
   - nova-controller

- hosts: compute-nodes
  roles:
   - ntp-other
   - infracommon
   - nova-compute

