---

- hosts: controller-nodes
  roles:
   - ntp-controller
   - infracommon
   - dbserver-maria
   - rabbitserver
   - memcached
   - dbserver_population
   - keystone
   - glance

- hosts: compute-nodes
  roles:
   - ntp-other
   - infracommon
