---
- name: ensure hosts is right
  lineinfile:
      dest: /etc/hosts
      state: present
      regexp: '{{ controller_ip }} controller'
      line: '{{ controller_ip }} controller'
  tags:
     - keystone 
     
- name: ensure hosts is right
  lineinfile:
      dest: /etc/hosts
      state: present
      regexp: '{{ compute_ip }} compute'
      line: '{{ compute_ip }} compute'
  tags:
     - keystone 

- name: Install pip 
  apt: name=python-pip state=present
  tags:
     - keystone  

- name: Update pip
#  pip: name=pip
  shell: sudo pip install --upgrade pip==9.0.1
  tags:
     - keystone 

- name: Install shade
  pip: name=shade state=present
  tags:
     - keystone  
     
- name: Install keystone packages
  apt: name={{ item }} state=installed force=yes
  with_items:
    - keystone
  tags:
     - keystone  

- name: Copy keystone.conf file
  template: src=keystone.j2 dest=/etc/keystone/keystone.conf
  tags:
     - keystone

- name: Syncing keystone database
  shell: sudo -s /bin/sh -c "keystone-manage db_sync" keystone
  tags:
     - keystone

- name: Initialize Fernet key repositories
  shell: keystone-manage {{ item }} --keystone-user keystone --keystone-group keystone
  with_items:
    - fernet_setup
    - credential_setup
  tags:
     - keystone

- name: Bootstrap the Identity service
  command: |
     keystone-manage bootstrap \
     --bootstrap-password {{ admin_pass }} \
     --bootstrap-admin-url http://controller:35357/v3 \
     --bootstrap-public-url http://controller:5000/v3 \
     --bootstrap-internal-url http://controller:5000/v3\
     --bootstrap-region-id RegionOne
  tags:
    - keystone

- name: Configure the Apache HTTP server
  template: src=apache2.j2 dest=/etc/apache2/apache2.conf
  notify:
   - restart apache2
  tags:
     - keystone

- name: Remove the default SQLite database on Controller Node
  command: rm -f /var/lib/keystone/keystone.db
  tags:
     - keystone

- name: Creating the admin-openrc  file in the /root directory
  template: src=admin-openrc.j2 dest=/root/admin-openrc owner=root group=root mode=0755
  tags:
     - keystone
 
- name: Creating the demo-openrc  file in the /root directory
  template: src=demo-openrc.j2 dest=/root/demo-openrc owner=root group=root mode=0755
  tags:
     - keystone

- name: update
  apt: update_cache=yes
######=============================================================================================
- name: Create OS service project
  os_project: domain_id=default description="Service Project" state=present
              name=service
  environment: "{{ admin_env }}"
  tags:
     - keystone

- name: Create demo project
  os_project: domain_id=default description="Demo Project" state=present
              name=demo
  environment: "{{ admin_env }}"
  tags:
     - keystone

- name: Create demo user
  os_user: name=demo password={{ admin_pass }} domain=default
  environment: "{{ admin_env }}"
  tags:
     - keystone

- name: Create user role
  os_keystone_role: name=user state=present
  environment: "{{ admin_env }}"
  tags:
     - keystone

- name: Add the user role to the demo project and user
  os_user_role: user=demo role=user project=demo state=present
  environment: "{{ admin_env }}"
  tags:
     - keystone
