- name: Installing the packages required for the database on the Controller
  apt: name="{{ item }}" state=installed
  with_items:
    - mariadb-server
    - python-pymysql
    - python-setuptools
    - libmysqld-dev
    - libmysqlclient-dev
    - python-dev
    
- name: Installing the MySQL-python
  easy_install: name=mysql-python state=latest

- name: Configuring the mysql server for the Openstack services
  template: src=99-openstack.cnf.j2 dest=/etc/mysql/mariadb.conf.d/99-openstack.cnf

- name: ensure the service is starting 
  service: name=mysql state=started enabled=yes


- name: Sets the root password
  mysql_user: name=root password="{{ root_db_password }}" host={{ item }}
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: 
    name: ''
    host: localhost
    state: absent

- name: Removes the MySQL test database
  mysql_db: db=test state=absent
  
- name: restart mysql
  service: name=mysql state=restarted